export const animalSounds = [
  { name: 'duck', src: '/sounds/duck.mp4' },
//   { name: 'cow', src: '/sounds/cow1.mp3' },
//   { name: 'duck', src: '/sounds/duck1.mp3' },
//   { name: 'falcon', src: '/sounds/falcon1.mp3' },
//   { name: 'pig', src: '/sounds/pig1.mp3' },
//   { name: 'crow', src: '/sounds/crow1.mp3' },
//   { name: 'cow', src: '/sounds/cow2.mp3' },
//   { name: 'dog', src: '/sounds/dog2.mp3' },
//   { name: 'duck', src: '/sounds/duck2.mp3' },
//   { name: 'pig', src: '/sounds/pig2.mp3' },
//   { name: 'crow', src: '/sounds/crow2.mp3' },
//   { name: 'falcon', src: '/sounds/falcon2.mp3' },
//   { name: 'cow', src: '/sounds/cow3.mp3' },
//   { name: 'duck', src: '/sounds/duck3.mp3' },
//   { name: 'dog', src: '/sounds/dog3.mp3' },
//   { name: 'falcon', src: '/sounds/falcon3.mp3' },
//   { name: 'pig', src: '/sounds/pig3.mp3' },
//   { name: 'crow', src: '/sounds/crow3.mp3' },
//   { name: 'dog', src: '/sounds/dog4.mp3' },
//   { name: 'cow', src: '/sounds/cow4.mp3' },
];
